#!/sbin/busybox sh

cd /

mount -t proc proc /proc
mount -t sysfs sysfs /sys

mkdir -p /dev/block
mknod /dev/block/mmcblk0p37 b 179 37

mkdir /data
mount -t ext4 /dev/block/mmcblk0p37 /data

ROM=`cat /data/media/.rom`

if grep -q "androidboot.mode=recovery" /proc/cmdline ; then
  mv -f /res/recovery/* /
  else
    mv -f /res/boot/* /
    if [ "$ROM" == "2" ]; then
    mv -f /init.qcom.rc.third /init.qcom.rc
    elif [ "$ROM" == "3" ]; then
    mv -f /init.qcom.rc.fourth /init.qcom.rc
    elif [ "$ROM" == "4" ]; then
    mv -f /init.qcom.rc.fifth /init.qcom.rc
  fi
fi

umount -f /data

chmod 755 /int.0
chmod 644 /*.qcom
chmod 644 /*.rc
chmod 644 /*.prop

rm /init
mv -f /init.0 /init

exec /init
