#!/sbin/busybox sh

cd /

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

mkdir -p /dev/block
mknod /dev/block/mmcblk0p37 b 179 37

mkdir /data
mount -t ext4 /dev/block/mmcblk0p37 /data

ROM=`cat /data/media/.rom`

if grep -q "androidboot.mode=recovery" /proc/cmdline ; then
  mv -f /res/recovery/* /
else
  mv -f /res/boot/* /
  if [ "$ROM" == "2" ]; then
    mv -f /init.rc.third /init.rc
    mv -f /init.qcom.rc.third /init.qcom.rc
  fi
fi

umount -f /data

chmod 755 /int.0
chmod 644 /*.qcom
chmod 644 /*.rc
chmod 644 /*.prop

rm /init
mv -f /init.0 /init

exec /init
